
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: develop-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: develop-pv
