
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: develop-home-pvc
spec:
  storageClassName: "rook-cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
