---
apiVersion: v1
kind: Service
metadata:
  name: develop-svc
spec:
  selector:
    app: develop
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      name: "ssh"
    - protocol: TCP
      port: 7521
      targetPort: 22
      name: "ssh-external"
  type: LoadBalancer
