name: cd-dev-base
on:
  push:
    paths:
      - dev-base
      - .github/workflows/cd-dev-base.yml
      - .github/workflows/release.yml
    branches:
      - main

jobs:
  ktse:
    uses: ./.github/workflows/release.yml
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      name: dev-base
      manifestFile: ""
      harborProject: "library"
      repository: ""
      harborUser: "robot$develop"
      dockerFile: './dev-base/Dockerfile'
      context: './dev-base'
