on:
  push:
    branches:
      - "main"
jobs:
  cd:
    strategy:
      matrix:
        conf:
          - dir: develop
            harbor-project: library
            artifact-name: dev-server
    runs-on: ubuntu-latest
    env:
      preDockerBuildCmd: ""
      manifest-repo: kigawa01/k8s-system
      manifestFile: ./develop/develop.yml
      dockerFile: Dockerfile
      harbor-user: robot$develop
      harbor-repo:
        harbor.kigawa.net/${{ matrix.conf.harbor-project }}/${{ matrix.conf.artifact-name }}:${{ github.ref_name }}-${{ github.sha }}
      dockerArg: ""
      dir: ${{ matrix.conf.dir }}
    steps:
      # checkout
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: hash
          key: hash-${{ matrix.conf.dir }}-${{ matrix.conf.harbor-project }}-${{ matrix.conf.artifact-name }}
      - run: |
          set -ue
          if [ ! -d hash ]; then
            mkdir hash
          fi
          if [ -f hash/hash ]; then
            echo find cache
            PREV_HASH=$(cat hash/hash) 
            echo "PREV_HASH=$PREV_HASH"
          else
            PREV_HASH=""
          fi
          SHA256_OUTPUT=$(\
            find "develop" -type f -print0 | \
            sort --zero-terminated | \
            xargs -0 sha256sum | \
            cut -d ' ' -f 1 | \
            sha256sum | \
            cut -d ' ' -f 1)
          CURRENT="artifacts=$SHA256_OUTPUT"
          echo "current hash: $CURRENT"
          echo "$CURRENT" > hash/hash
          if [ "$PREV_HASH" == "$CURRENT" ]; then
            echo match hash
            ECECUTE=1
          else
            echo not match hash
            ECECUTE=0
          fi
          echo "ECECUTE=$ECECUTE"
          set +ue

      # cmd
      - name: preBuild
        if: env.ECECUTE  && env.preDockerBuildCmd
        run: ${{ env.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        if: env.ECECUTE
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: env.ECECUTE
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harbor-user }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: BuildAndPushImageOnHarbor
        if: env.ECECUTE
        run: |
          docker build -t ${{ env.harbor-repo }} \
           -f ${{ env.dir }}/${{ env.dockerFile }} ${{ env.dockerArg }} ${{ env.dir }}
          docker push \
          ${{ env.harbor-repo }}


      - name: checkout manifest repository
        if: env.ECECUTE
        uses: actions/checkout@v3
        with:
          repository: ${{ env.manifest-repo }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        if: env.ECECUTE
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ env.harbor-repo }}"' \
          ${{ env.manifestFile }}

      - name: push
        if: env.ECECUTE
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
