on:
  push:
    branches:
      - "main"
jobs:
  cd:
    strategy:
      matrix:
        conf:
          - dir: develop
            harbor-project: library
            artifact-name: dev-server
    runs-on: ubuntu-latest
    env:
      preDockerBuildCmd: ""
      manifest-repo: kigawa01/k8s-system
      manifestFile: ./develop/develop.yml
      dockerFile: Dockerfile
      harbor-user: robot$develop
      harbor-repo:
        harbor.kigawa.net/${{ matrix.conf.harbor-project }}/${{ matrix.conf.artifact-name }}:${{ github.ref_name }}-${{ github.sha }}
      dockerArg: ""
      dir: ${{ matrix.conf.dir }}
    steps:
      # checkout
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: hash
          key: hash-${{ matrix.conf.dir }}-${{ matrix.conf.harbor-project }}-${{ matrix.conf.artifact-name }}
      - run: |
          if [ -f /hash/hash ]; then
            cat /hash/hash >> $PREV_HASH
          else
            PREV_HASH=""
          fi
          set -x  # 後のパイプの処理がどこまで進んだかわかりやすくするために -x する
          SHA256_OUTPUT=$(find ${{ matrix.conf.dir }} -type f -print0 | \  # 実際にハッシュ値を計算する部分
          sort --zero-terminated | \
          xargs -0 sha256sum | \
          cut -d ' ' -f 1 | \
          sha256sum | \
          cut -d ' ' -f 1)
          set +x  # -x を解除
          echo "artifacts=$SHA256_OUTPUT" >> $HASH
          echo "$HASH" > /hash/hash

      # cmd
      - name: preBuild
        if: env.HASH != env.PREV_HASH && env.preDockerBuildCmd
        run: ${{ env.preDockerBuildCmd }}

      # docker
      - name: Set up Docker Buildx
        if: env.HASH != env.PREV_HASH
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: env.HASH != env.PREV_HASH
        with:
          registry: harbor.kigawa.net
          username: ${{ env.harbor-user }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: BuildAndPushImageOnHarbor
        if: env.HASH != env.PREV_HASH
        run: |
          docker build -t ${{ env.harbor-repo }} \
           -f ${{ env.dir }}/${{ env.dockerFile }} ${{ env.dockerArg }} ${{ env.dir }}
          docker push \
          ${{ env.harbor-repo }}


      - name: checkout manifest repository
        if: env.HASH != env.PREV_HASH
        uses: actions/checkout@v3
        with:
          repository: ${{ env.manifest-repo }}
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        if: env.HASH != env.PREV_HASH
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ env.harbor-repo }}"' \
          ${{ env.manifestFile }}

      - name: push
        if: env.HASH != env.PREV_HASH
        run: |
          git config user.name githubActions
          git config user.email bot@kigawa.net
          git add .
          git commit --author=. -m "update rev"
          git push
